-- MySQL Script generated by MySQL Workbench
-- Tue Feb 21 20:17:31 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema board
-- -----------------------------------------------------
-- 实时共享白板数据库
-- /**
--  *
--  * ━━━━━━神兽出没━━━━━━
--  * 　　　┏┓　　　┏┓
--  * 　　┏┛┻━━━┛┻┓
--  * 　　┃　　　　　　　┃
--  * 　　┃　　　━　　　┃
--  * 　　┃　┳┛　┗┳　┃
--  * 　　┃　　　　　　　┃
--  * 　　┃　　　┻　　　┃
--  * 　　┃　　　　　　　┃
--  * 　　┗━┓　　　┏━┛Code is far away from bug with the animal protecting
--  * 　　　　┃　　　┃    神兽保佑,代码无bug
--  * 　　　　┃　　　┃
--  * 　　　　┃　　　┗━━━┓
--  * 　　　　┃　　　　　　　┣┓
--  * 　　　　┃　　　　　　　┏┛
--  * 　　　　┗┓┓┏━┳┓┏┛
--  * 　　　　　┃┫┫　┃┫┫
--  * 　　　　　┗┻┛　┗┻┛
--  *
--  * ━━━━━━感觉萌萌哒━━━━━━
--  */
--   
-- /**
--  * 　　　　　　　　┏┓　　　┏┓
--  * 　　　　　　　┏┛┻━━━┛┻┓
--  * 　　　　　　　┃　　　　　　　┃ 　
--  * 　　　　　　　┃　　　━　　　┃
--  * 　　　　　　　┃　＞　　　＜　┃
--  * 　　　　　　　┃　　　　　　　┃
--  * 　　　　　　　┃...　⌒　...　┃
--  * 　　　　　　　┃　　　　　　　┃
--  * 　　　　　　　┗━┓　　　┏━┛
--  * 　　　　　　　　　┃　　　┃　Code is far away from bug with the animal protecting　　　　　　　　　　
--  * 　　　　　　　　　┃　　　┃   神兽保佑,代码无bug
--  * 　　　　　　　　　┃　　　┃　　　　　　　　　　　
--  * 　　　　　　　　　┃　　　┃  　　　　　　
--  * 　　　　　　　　　┃　　　┃
--  * 　　　　　　　　　┃　　　┃　　　　　　　　　　　
--  * 　　　　　　　　　┃　　　┗━━━┓
--  * 　　　　　　　　　┃　　　　　　　┣┓
--  * 　　　　　　　　　┃　　　　　　　┏┛
--  * 　　　　　　　　　┗┓┓┏━┳┓┏┛
--  * 　　　　　　　　　　┃┫┫　┃┫┫
--  * 　　　　　　　　　　┗┻┛　┗┻┛
--  */
--   
-- /**
--  *　　　　　　　　┏┓　　　┏┓+ +
--  *　　　　　　　┏┛┻━━━┛┻┓ + +
--  *　　　　　　　┃　　　　　　　┃ 　
--  *　　　　　　　┃　　　━　　　┃ ++ + + +
--  *　　　　　　 ████━████ ┃+
--  *　　　　　　　┃　　　　　　　┃ +
--  *　　　　　　　┃　　　┻　　　┃
--  *　　　　　　　┃　　　　　　　┃ + +
--  *　　　　　　　┗━┓　　　┏━┛
--  *　　　　　　　　　┃　　　┃　　　　　　　　　　　
--  *　　　　　　　　　┃　　　┃ + + + +
--  *　　　　　　　　　┃　　　┃　　　　Code is far away from bug with the animal protecting　　　　　　　
--  *　　　　　　　　　┃　　　┃ + 　　　　神兽保佑,代码无bug　　
--  *　　　　　　　　　┃　　　┃
--  *　　　　　　　　　┃　　　┃　　+　　　　　　　　　
--  *　　　　　　　　　┃　 　　┗━━━┓ + +
--  *　　　　　　　　　┃ 　　　　　　　┣┓
--  *　　　　　　　　　┃ 　　　　　　　┏┛
--  *　　　　　　　　　┗┓┓┏━┳┓┏┛ + + + +
--  *　　　　　　　　　　┃┫┫　┃┫┫
--  *　　　　　　　　　　┗┻┛　┗┻┛+ + + +
--  */

-- -----------------------------------------------------
-- Schema board
--
-- 实时共享白板数据库
-- /**
--  *
--  * ━━━━━━神兽出没━━━━━━
--  * 　　　┏┓　　　┏┓
--  * 　　┏┛┻━━━┛┻┓
--  * 　　┃　　　　　　　┃
--  * 　　┃　　　━　　　┃
--  * 　　┃　┳┛　┗┳　┃
--  * 　　┃　　　　　　　┃
--  * 　　┃　　　┻　　　┃
--  * 　　┃　　　　　　　┃
--  * 　　┗━┓　　　┏━┛Code is far away from bug with the animal protecting
--  * 　　　　┃　　　┃    神兽保佑,代码无bug
--  * 　　　　┃　　　┃
--  * 　　　　┃　　　┗━━━┓
--  * 　　　　┃　　　　　　　┣┓
--  * 　　　　┃　　　　　　　┏┛
--  * 　　　　┗┓┓┏━┳┓┏┛
--  * 　　　　　┃┫┫　┃┫┫
--  * 　　　　　┗┻┛　┗┻┛
--  *
--  * ━━━━━━感觉萌萌哒━━━━━━
--  */
--   
-- /**
--  * 　　　　　　　　┏┓　　　┏┓
--  * 　　　　　　　┏┛┻━━━┛┻┓
--  * 　　　　　　　┃　　　　　　　┃ 　
--  * 　　　　　　　┃　　　━　　　┃
--  * 　　　　　　　┃　＞　　　＜　┃
--  * 　　　　　　　┃　　　　　　　┃
--  * 　　　　　　　┃...　⌒　...　┃
--  * 　　　　　　　┃　　　　　　　┃
--  * 　　　　　　　┗━┓　　　┏━┛
--  * 　　　　　　　　　┃　　　┃　Code is far away from bug with the animal protecting　　　　　　　　　　
--  * 　　　　　　　　　┃　　　┃   神兽保佑,代码无bug
--  * 　　　　　　　　　┃　　　┃　　　　　　　　　　　
--  * 　　　　　　　　　┃　　　┃  　　　　　　
--  * 　　　　　　　　　┃　　　┃
--  * 　　　　　　　　　┃　　　┃　　　　　　　　　　　
--  * 　　　　　　　　　┃　　　┗━━━┓
--  * 　　　　　　　　　┃　　　　　　　┣┓
--  * 　　　　　　　　　┃　　　　　　　┏┛
--  * 　　　　　　　　　┗┓┓┏━┳┓┏┛
--  * 　　　　　　　　　　┃┫┫　┃┫┫
--  * 　　　　　　　　　　┗┻┛　┗┻┛
--  */
--   
-- /**
--  *　　　　　　　　┏┓　　　┏┓+ +
--  *　　　　　　　┏┛┻━━━┛┻┓ + +
--  *　　　　　　　┃　　　　　　　┃ 　
--  *　　　　　　　┃　　　━　　　┃ ++ + + +
--  *　　　　　　 ████━████ ┃+
--  *　　　　　　　┃　　　　　　　┃ +
--  *　　　　　　　┃　　　┻　　　┃
--  *　　　　　　　┃　　　　　　　┃ + +
--  *　　　　　　　┗━┓　　　┏━┛
--  *　　　　　　　　　┃　　　┃　　　　　　　　　　　
--  *　　　　　　　　　┃　　　┃ + + + +
--  *　　　　　　　　　┃　　　┃　　　　Code is far away from bug with the animal protecting　　　　　　　
--  *　　　　　　　　　┃　　　┃ + 　　　　神兽保佑,代码无bug　　
--  *　　　　　　　　　┃　　　┃
--  *　　　　　　　　　┃　　　┃　　+　　　　　　　　　
--  *　　　　　　　　　┃　 　　┗━━━┓ + +
--  *　　　　　　　　　┃ 　　　　　　　┣┓
--  *　　　　　　　　　┃ 　　　　　　　┏┛
--  *　　　　　　　　　┗┓┓┏━┳┓┏┛ + + + +
--  *　　　　　　　　　　┃┫┫　┃┫┫
--  *　　　　　　　　　　┗┻┛　┗┻┛+ + + +
--  */
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `board` DEFAULT CHARACTER SET utf8 ;
USE `board` ;

-- -----------------------------------------------------
-- Table `board`.`bd_version`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `board`.`bd_version` ;

CREATE TABLE IF NOT EXISTS `board`.`bd_version` (
  `version_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `version_part_one` SMALLINT UNSIGNED NOT NULL COMMENT '主版本号',
  `version_part_two` SMALLINT UNSIGNED NOT NULL COMMENT '子版本号',
  `version_part_three` SMALLINT UNSIGNED NOT NULL COMMENT '修订版本号',
  `version_part_four` INT UNSIGNED NOT NULL COMMENT '日期版本号',
  `version_part_five` CHAR(10) NOT NULL COMMENT '希腊字母版本号',
  PRIMARY KEY (`version_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `board`.`bd_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `board`.`bd_user` ;

CREATE TABLE IF NOT EXISTS `board`.`bd_user` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_email` VARCHAR(45) NOT NULL COMMENT '邮箱',
  `user_family_name` VARCHAR(15) NOT NULL COMMENT '姓',
  `user_given_name` VARCHAR(15) NOT NULL COMMENT '名',
  `user_register_time` DATETIME NOT NULL COMMENT '注册时间',
  `user_login_recent_time` DATETIME NOT NULL COMMENT '最近登录时间',
  `user_status` INT UNSIGNED NOT NULL DEFAULT 1 COMMENT '用户状态：1：未登录 2 ：登录空闲  会议ID: 登录会议中',
  `user_class` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '用户等级：1：免费用户 2：普通会员 3.超级会员',
  `user_password` CHAR(16) NOT NULL COMMENT '密码',
  PRIMARY KEY (`user_id`, `user_email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `board`.`bd_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `board`.`bd_log` ;

CREATE TABLE IF NOT EXISTS `board`.`bd_log` (
  `log_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NULL COMMENT '出现问题的用户ID',
  `log_device_info` VARCHAR(45) NULL COMMENT '设备信息',
  `log_error_info` TEXT NULL COMMENT '报错信息',
  `log_app_version` VARCHAR(45) NULL COMMENT '应用程序版本',
  PRIMARY KEY (`log_id`),
  INDEX `user_id_idx` (`user_id` ASC),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `board`.`bd_user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `board`.`bd_reset_password`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `board`.`bd_reset_password` ;

CREATE TABLE IF NOT EXISTS `board`.`bd_reset_password` (
  `reset_id` INT NOT NULL AUTO_INCREMENT,
  `reset_target_user_email` VARCHAR(45) NOT NULL COMMENT '重置目标用户ID',
  `reset_token` TINYINT NOT NULL COMMENT '验证码',
  `reset_begin_time` DATETIME NOT NULL COMMENT '最近发送验证码的时间点（验证码2分钟有效）',
  `reset_result` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '重置结果：1：失败 2：成功',
  PRIMARY KEY (`reset_id`),
  INDEX `reset_target_user_email_idx` (`reset_target_user_email` ASC),
  CONSTRAINT `reset_target_user_email`
    FOREIGN KEY (`reset_target_user_email`)
    REFERENCES `board`.`bd_user` (`user_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `board`.`bd_meeting`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `board`.`bd_meeting` ;

CREATE TABLE IF NOT EXISTS `board`.`bd_meeting` (
  `meeting_id` INT UNSIGNED NOT NULL,
  `meeting_url` INT UNSIGNED NULL COMMENT '9位数字 xxx-xxx-xxx',
  `meeting_title` VARCHAR(40) NOT NULL COMMENT '预定会议主题',
  `meeting_host_user_id` INT UNSIGNED NOT NULL,
  `meeting_is_drawable` TINYINT NOT NULL COMMENT '与会者默认可画  1 不能 2 可以',
  `meeting_is_talkable` TINYINT NOT NULL COMMENT '与会者默认可说 1 不能 2 可以',
  `meeting_is_use_pmi` TINYINT NOT NULL DEFAULT 1 COMMENT '是否使用个人会议ID 1：不使用 2 ：使用',
  `meeting_is_add_to_calendar` TINYINT NOT NULL DEFAULT 1 COMMENT '是否添加到日历 1：不添加 2：添加',
  `meeting_password` CHAR(8) NULL COMMENT '密码可空',
  `meeting_start_time` DATETIME NOT NULL COMMENT '会议开始时间',
  `meeting_end_time` DATETIME NOT NULL,
  `meeting_status` TINYINT NOT NULL DEFAULT 1 COMMENT '预约状态：1 ：未开始并且未到期 2：未开始并且过期了 3：正在进行 4：开会结束 ',
  PRIMARY KEY (`meeting_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `board`.`bd_user_and_meeting`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `board`.`bd_user_and_meeting` ;

CREATE TABLE IF NOT EXISTS `board`.`bd_user_and_meeting` (
  `user_and_meeting_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL COMMENT '用户id',
  `meeting_id` INT UNSIGNED NOT NULL COMMENT '会议ID',
  `type` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '参会类型：1 ：与会 2：主持会议',
  `check_in_time` DATETIME NOT NULL COMMENT '最早入会时间',
  `check_out_time` DATETIME NOT NULL COMMENT '最迟离会时间',
  PRIMARY KEY (`user_and_meeting_id`),
  INDEX `user_id_idx` (`user_id` ASC),
  INDEX `meeting_id_idx` (`meeting_id` ASC),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `board`.`bd_user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `meeting_id`
    FOREIGN KEY (`meeting_id`)
    REFERENCES `board`.`bd_meeting` (`meeting_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `board`.`bd_add_friend`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `board`.`bd_add_friend` ;

CREATE TABLE IF NOT EXISTS `board`.`bd_add_friend` (
  `add_friend_id` INT UNSIGNED NOT NULL,
  `request_user_id` INT UNSIGNED NOT NULL,
  `target_user_id` INT UNSIGNED NOT NULL,
  `response_status` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '回复状态：1：未回复 2：拒绝 3：同意',
  `message_time` DATETIME NOT NULL COMMENT '消息时间',
  PRIMARY KEY (`add_friend_id`),
  INDEX `request_user_id_idx` (`request_user_id` ASC),
  INDEX `target_user_id_idx` (`target_user_id` ASC),
  CONSTRAINT `request_user_id`
    FOREIGN KEY (`request_user_id`)
    REFERENCES `board`.`bd_user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `target_user_id`
    FOREIGN KEY (`target_user_id`)
    REFERENCES `board`.`bd_user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
